from __future__ import annotations
import asyncio
from typing import Any, Dict, Optional

from app.core.perf_tracer import PerformanceTracer

from app.core.observability import get_logger

from app.ai.intent_detector import IntentDetector
from app.ai.intent_router import IntentRouter
from app.ai.prompt_builder import PromptBuilder
from app.models.chatbot.message import MessageRole
from app.schemas.chat_dtos import ChatDomainRequest, ChatDomainResponse
from app.services.ai_orchestrator import AIOrchestrator

logger = get_logger(__name__)


class ChatService:
    """
    100% Agnostic Domain Service.
    Operates on pure AI logic and returns domain results with opaque metadata.
    """
    STATIC_INTENTS = {"greeting", "general_faq", "chit_chat", "fallback"}

    def __init__(
        self,
        ai_orchestrator: AIOrchestrator,
        intent_detector: IntentDetector,
        intent_router: IntentRouter,
        prompt_builder: PromptBuilder,
        semantic_cache=None,
    ):
        self.orchestrator = ai_orchestrator
        self.intent_detector = intent_detector
        self.intent_router = intent_router
        self.prompt_builder = prompt_builder
        self.semantic_cache = semantic_cache

    def _get_cache_scope(self, intent: str, session_id: str) -> Optional[str]:
        """
        Determines the isolation scope for semantic caching.
        - general_faq: Global (None) - strictly impersonal, safe to share.
        - fallback, greeting, chit_chat: Session-scoped - might contain PII (e.g. user names generated by LLM).
        """
        return None if intent == "general_faq" else session_id

    async def generate_response(
        self,
        domain_request: ChatDomainRequest,
    ) -> ChatDomainResponse:
        """
        AI Domain Pipeline.
        Returns result and metadata that the Application Layer interprets.
        """
        tracer = PerformanceTracer()
        
        # 1. Intent & Routing
        with tracer.step("intent_detection"):
            intent_result = await self.intent_detector.detect_complex(domain_request.message)
            routing = self.intent_router.route(intent_result)
            intent_tokens = intent_result.get("tokens", 0) if intent_result else 0
        logger.info("chat.intent_detected", intent=routing["intent"], confidence=routing["confidence"], route=routing["route"])
        
        # 1.5 Semantic Cache Check (Only for Static Intents)
        if self.semantic_cache and routing["intent"] in self.STATIC_INTENTS:
            with tracer.step("semantic_cache_search"):
                cache_user_id = self._get_cache_scope(routing["intent"], domain_request.context.session_id)
                cached_data = await asyncio.to_thread(
                    self.semantic_cache.search,
                    domain_request.message, 
                    user_id=cache_user_id, 
                    expected_intent=routing["intent"]
                )
                if cached_data:
                    tracer.log_summary(logger, layer="domain", session_id=domain_request.context.session_id)
                    return ChatDomainResponse(
                        content=cached_data.get("response", ""),
                        role=MessageRole.assistant,
                        intent=routing["intent"],
                        confidence=routing["confidence"],
                        route=routing["route"],
                        ai_tokens=intent_tokens,
                        tool_results=[],
                        latency_ms=int(tracer.total_ms),
                        token_breakdown={
                            "intent_tokens": intent_tokens, 
                            "cached": True,
                            "planner_prompt_tokens": 0,
                            "planner_completion_tokens": 0,
                            "renderer_prompt_tokens": 0,
                            "renderer_completion_tokens": 0,
                            "tool_result_tokens": 0,
                        }
                    )
        
        # 2. Construction
        with tracer.step("prompt_construction"):
            system_prompt = self.prompt_builder.build_system_prompt(domain_request.context, routing["intent"])
            renderer_prompt = self.prompt_builder.build_renderer_prompt(domain_request.context, routing["intent"])
            history_formatted = self.prompt_builder.build_history(domain_request.history)

        # 3. Generation
        logger.info("chat.generation_started", intent=routing["intent"], route=routing["route"])
        with tracer.step("ai_generation"):
            content, ai_tokens, tools, token_breakdown = await self.orchestrator.generate_complex(
                user_input=domain_request.message,
                intent=routing["intent"],
                payload={
                    "system_prompt": system_prompt,
                    "renderer_prompt": renderer_prompt,
                    "history": history_formatted,
                    "context": domain_request.context,
                    "model": domain_request.context.model_name
                },
                session_id=domain_request.context.session_id,
                route=routing["route"]
            )
            
            # Add intent tokens to the breakdown
            token_breakdown["intent_tokens"] = intent_tokens
            token_breakdown["cached"] = False
            ai_tokens += intent_tokens

        # 3.5 Store in Semantic Cache
        if self.semantic_cache and routing["intent"] in self.STATIC_INTENTS:
            cache_user_id = self._get_cache_scope(routing["intent"], domain_request.context.session_id)
            await asyncio.to_thread(
                self.semantic_cache.add,
                domain_request.message, 
                content, 
                routing["intent"], 
                user_id=cache_user_id
            )

        # 4. Result Construction (Agnostic Metadata)
        tracer.log_summary(logger, layer="domain", session_id=domain_request.context.session_id)
        return ChatDomainResponse(
            content=content,
            role=MessageRole.assistant,
            intent=routing["intent"],
            confidence=routing["confidence"],
            route=routing["route"],
            ai_tokens=ai_tokens,
            tool_results=tools,
            latency_ms=int(tracer.total_ms),
            token_breakdown=token_breakdown
        )
