from __future__ import annotations

import inspect
from dataclasses import dataclass
from typing import Any, Callable


@dataclass
class ToolDefinition:
    """
    Represents the definition of a tool that the AI can call.
    It includes the tool's name, purpose, input parameters, and the actual function to run.
    """
    name: str
    description: str
    parameters: dict[str, Any]
    func: Callable[..., Any]


class ToolRegistry:
    """
    The ToolRegistry keeps track of all tools available to the AI.
    It allows you to register new tools and execute them when the AI requests it.
    """
    def __init__(self):
        self._tools: dict[str, ToolDefinition] = {}

    def register(self, name: str, description: str, parameters: dict[str, Any]):
        """
        A decorator used to register a function as a tool.
        
        Args:
            name: The unique name of the tool.
            description: What the tool does (the AI uses this to decide when to call it).
            parameters: A JSON schema describing the inputs the tool expects.
        """
        def decorator(func: Callable[..., Any]):
            self._tools[name] = ToolDefinition(
                name=name,
                description=description,
                parameters=parameters,
                func=func
            )
            return func
        return decorator

    def get_tool_definitions(self) -> list[dict[str, Any]]:
        """
        Returns a list of all registered tool definitions in a format the AI understands.
        """
        return [
            {
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.parameters,
            }
            for tool in self._tools.values()
        ]

    def get_tool(self, name: str) -> ToolDefinition | None:
        """Finds a tool by its name."""
        return self._tools.get(name)

    async def call_tool(
        self,
        name: str,
        runtime_deps: dict[str, Any] | None = None,
        **kwargs
    ) -> Any:
        """
        Executes a specific tool by name with the provided arguments.
        
        Args:
            name: The name of the tool to call.
            runtime_deps: Extra data to pass to the tool (like user info).
            **kwargs: The arguments generated by the AI for the tool.
        """
        tool = self.get_tool(name)
        if not tool:
            raise ValueError(f"Tool {name} not found")

        # Merge AI-generated arguments with system-provided dependencies
        if runtime_deps:
            kwargs = {**kwargs, **runtime_deps}
        
        # Check if the tool function is async or normal and run it accordingly.
        if inspect.iscoroutinefunction(tool.func):
            return await tool.func(**kwargs)
        return tool.func(**kwargs)
